#!/usr/bin/env python3

import sys
from math import *
import numpy as np
import time

import rospy
import actionlib
from actionlib_msgs.msg import GoalStatus
from geometry_msgs.msg import Point, PoseStamped
from spar_msgs.msg import FlightMotionAction, FlightMotionGoal
from breadcrumb.srv import RequestPath, RequestPathRequest

# This is getting a bit more complicated now, so we'll put our information in
# a class to keep track of all of our variables. This is not so much different
# to the previous methods, other than the fact that the class will operate
# within itself.
# i.e. it will have it's own publishers, subscribers, etc., that
# will call it's own functions as callbacks, etc.
class Guidance():
	def __init__(self, waypoints):
		# Make sure we have a valid waypoint list
		if not self.check_waypoints(waypoints):
			raise ArgumentError("Invalid waypoint list input!")

		# Internal counter to see what waypoint were are up to
		self.waypoint_counter = 0

		# Set a flag to indicate that we are doing a specific inspection
		# and that we are not following our waypoint list
		# This will stop our "waypoint is reached" callback from firing
		# during the roi diversion and taking over our flight!
		self.performing_roi = False

		# Save the input waypoints
		self.waypoints = waypoints

		# Make some space to record down our current location
		self.current_location = Point()
		# Set our linear and rotational velocities for the flight
		self.vel_linear = rospy.get_param("~vel_linear", 0.2)
		self.vel_yaw = rospy.get_param("~vel_yaw", 0.2)
		# Set our position and yaw waypoint accuracies
		self.accuracy_pos = rospy.get_param("~acc_pos", 0.1)
		self.accuracy_yaw = rospy.get_param("~acc_yaw", 0.1)

		# Create our action client
		action_ns = rospy.get_param("~action_topic", 'spar/flight')
		self.spar_client = actionlib.SimpleActionClient(action_ns, FlightMotionAction)
		rospy.loginfo("Waiting for spar...")
		self.spar_client.wait_for_server()

		if not rospy.is_shutdown():
			# Good to go, start mission
			rospy.loginfo("Starting waypoint mission")

			# Setup first waypoint segment
			# XXX:	Another option would be to do "takeoff" and leave "waypoint_counter = 0" to
			#		begin the mission at the first waypoint after take-off
			self.send_wp(self.waypoints[0])
			self.waypoint_counter += 1

			# Setup a timer to check if our waypoint has completed at 20Hz
			self.timer = rospy.Timer( rospy.Duration(1.0/20.0), self.check_waypoint_status )
			# Callback to save "current location" such that we can perform and return
			# from a diversion to the correct location
			# XXX: These topics could be hard-coded to avoid using a launch file
			self.sub_pose = rospy.Subscriber("~pose", PoseStamped, self.callback_pose)
			# Subscriber to catch "ROI" diversion commands
			self.sub_roi = rospy.Subscriber("~roi", PoseStamped, self.callback_inspect_roi)

			# XXX: Could have a publisher to output our waypoint progress
			# throughout the flight (should publish each time the waypoint
			# counter is increased). Note: will also need to import "Float32"
			# from "std_msgs.msg" in the header
			# self.pub_progress = rospy.Subscriber("~waypoint_progress", Float32, 10)

			# If shutdown is issued (eg. CTRL+C), cancel current
	 		# mission before rospy is shutdown.
			rospy.on_shutdown( lambda : self.shutdown() )

	# This function will check if a list of waypoints is in the format we expect
	def check_waypoints(self, wps):
		# Make sure waypoints are a list
		if not isinstance(wps, list):
			rospy.logwarn("Waypoints are not list")
			return False

		# Make sure we have at least one waypoint
		if len(wps) < 1:
			rospy.logwarn("Waypoints list is empty")
			return False

		# Check each of our waypoints
		for i in range(len(wps)):
			if not self.check_waypoint(wps[i]):
				rospy.logwarn("Waypoint %i did not pass check" % (i + 1))
				return False

		# If we haven't returned false yet, then waypoints look good!
		return True


	# This function will check if a waypoint is in the format we expect
	def check_waypoint(self, wp):
		# Make sure each waypoint is a list
		if not isinstance(wp, list):
			rospy.logwarn("Waypoint is not a list of coordinates")
			return False

		# Make sure each waypoint has 4 values
		if len(wp) != 4:
			rospy.logwarn("Waypoint has an invalid length (must be X/Y/Z/Yaw)")
			return False

		# If we haven't returned false yet, then waypoint looks valid!
		return True


	# This function will make sure we shut down the node as safely as possible
	def shutdown(self):
		# Unregister anything that needs it here
		self.sub_pose.unregister()
		self.sub_roi.unregister()
		self.spar_client.cancel_goal()

		rospy.loginfo("Guidance stopped")


	# This function will check receive the current pose of the UAV constantly
	def callback_pose(self, msg_in):
		# Store the current position at all times so it can be accessed later
		self.current_location = msg_in.pose.position


	# This function will fire whenever a ROI pose message is sent
	# It is also responsible for handling the ROI "inspection task"
	def callback_inspect_roi(self, msg_in):
		# Set our flag that we are performing the diversion
		self.performing_roi = True

		rospy.loginfo("Starting diversion to ROI...")
		# Cancel the current goal (if there is one)
		self.spar_client.cancel_goal()
		# Record our current location so we can return to it later
		start_location = self.current_location
		# XXX:	It would also be a good idea to capture "current yaw" from
		#		the pose to maintain that throughout a diversion

		# Set the "diversion waypoint" (at yaw zero)
		dwp = [msg_in.pose.position.x, msg_in.pose.position.y, msg_in.pose.position.z, 0.0]
		# Set the "return waypoint" (at yaw zero)
		rwp = [self.current_location.x, self.current_location.y, self.current_location.z, 0.0]

		# XXX: Could pause here for a moment with ( "rospy.sleep(...)" ) to make sure the UAV stops correctly

		self.send_wp(dwp)
		self.spar_client.wait_for_result()
		if self.spar_client.get_state() != GoalStatus.SUCCEEDED:
			# Something went wrong, cancel out of guidance!
			rospy.signal_shutdown("cancelled")
			return

		rospy.loginfo("Reached diversion ROI!")
		# XXX: Do something?
		# set msg_in to 0
		# rostopic pub /actuator_control/actuator_a std_msgs/UInt16 '{data:1,2,3}'
		rospy.sleep(rospy.Duration(10))

		rospy.loginfo("Returning to flight plan...")

		self.send_wp(rwp)
		self.spar_client.wait_for_result()
		if self.spar_client.get_state() != GoalStatus.SUCCEEDED:
			# Something went wrong, cancel out of guidance!
			rospy.signal_shutdown("cancelled")
			return

		# "waypoint_counter" represents the "next waypoint"
		# "waypoint_counter - 1" represents the "current waypoint"
		rospy.loginfo("Resuming flight plan from waypoint %i!" % (self.waypoint_counter - 1))
		self.send_wp(self.waypoints[self.waypoint_counter - 1])
		# Unset our flag that we are performing a diversion
		# to allow the waypoint timer to take back over
		self.performing_roi = False


	# This function is for convinience to simply send out a new waypoint
	def send_wp(self, wp):
		# Make sure the waypoint is valid before continuing
		if not self.check_waypoint(wp):
			raise ArgumentError("Invalid waypoint input!")

		# Build the flight goal
		goal = FlightMotionGoal()
		goal.motion = FlightMotionGoal.MOTION_GOTO
		goal.position.x = wp[0]
		goal.position.y = wp[1]
		goal.position.z = wp[2]
		goal.yaw = wp[3]
		goal.velocity_vertical = self.vel_linear
		goal.velocity_horizontal = self.vel_linear
		goal.yawrate = self.vel_yaw
		goal.wait_for_convergence = True
		goal.position_radius = self.accuracy_pos
		goal.yaw_range = self.accuracy_yaw

		# For this function, we don't wait in the loop.
		# Instead we just send the waypoint and check up on it later
		# This checking is either with the "self.timer" for waypoints
		# or with direct calls during the ROI diversion
		self.spar_client.send_goal(goal)
		 # If shutdown is issued, cancel current mission before rospy is shutdown
		rospy.on_shutdown(lambda : self.spar_client.cancel_goal())


	# This function will fire whenever we recieve a timer event (te) from rospy.Timer()
	# The main purpose is to check if a waypoint has been reached,
	# and if so, send out the next waypoint to continue the mission
	def check_waypoint_status(self, te):
		# If we're performing the ROI diversion, then don't do
		# anything here, as this is handled in that function
		if not self.performing_roi:
			# If the last segment has succeeded.
			# For more complex tasks, it might be necessary to also
			# check if you are in waypoint or diversion mode here.
			# Hint: really, we should check for other status states
			#		(such as aborted), as there are some states
			#		where we won't recover from, and should just exit
			if self.spar_client.get_state() == GoalStatus.SUCCEEDED:
				rospy.loginfo("Reached waypoint %i!" % (self.waypoint_counter))

				# XXX:	Another check could go here to finish the mission early
				#		if "all" inspection tasks have been completed
				#		(Add in another "if" and make the waypoint counter check
				#		 an "elif" check instead.
				#		 i.e. if complete; elif more wps; else wps finished)
				if self.waypoint_counter < (len(self.waypoints)):
					self.send_wp(self.waypoints[self.waypoint_counter])
					# Increment our waypoint counter
					self.waypoint_counter += 1
				else:
					# Else the mission is over, shutdown and quit the node
					# XXX:	This could be used to restart the mission back to the
					#		first waypoint instead to restart the mission
					rospy.loginfo("Mission complete!")
					rospy.signal_shutdown("complete")
			elif (self.spar_client.get_state() == GoalStatus.PREEMPTED) or (self.spar_client.get_state() == GoalStatus.ABORTED) or (self.spar_client.get_state() == GoalStatus.REJECTED):
				rospy.loginfo("Mission cancelled!")
				rospy.signal_shutdown("cancelled")

def generate_waypoints(width,height,x_edge_offset,y_edge_offset,alt):

	# Set altitude & YAW
	yaw = 0.0
	waypoints = []
	
	# Add takeoff waypoint (over origin of map)
	waypoints.append([0, 0, alt, 0])

	# Given width and height (cannot change these)
	width = 8
	height = 5

	# Define edge offsets
	x_edge_offset = 0.5
	y_edge_offset = 0.25

	# Density paramater
	dn = 1.5

	# Calculate spacings based on the defined edge offsets
	available_x_space = width - dn * x_edge_offset
	available_y_space = height - dn * y_edge_offset

	# Calculate spacing to ensure symmetry
	x_spacing = available_x_space / (int(available_x_space) // dn)
	y_spacing = available_y_space / (int(available_y_space) // dn)

	# Adjust the grid to have the origin in the center and stay within bounds
	x_points = np.arange(-width/2 + x_edge_offset, width/2 - x_edge_offset + x_spacing, x_spacing)
	y_points = np.arange(-height/2 + y_edge_offset, height/2 - y_edge_offset + y_spacing, y_spacing)

	# Traverse the area in a straight line along the x-axis (long axis)
	for x in x_points:
		for y in y_points:
			waypoints.append([x, y, alt, yaw])  # Initialize with z=0.0 and yaw=0.0
		y_points = y_points[::-1]  # Reverse y_points to keep a straight line in x direction

	# Add pre-landing waypoint (origin of map)
	waypoints.append([0, 0, alt, 0])

	# Remove the middle waypoint if three consecutive waypoints are aligned
	def remove_middle_if_aligned(waypoints):
		new_waypoints = []
		i = 0
		while i < len(waypoints):
			if i > 0 and i < len(waypoints) - 1:
				prev_wp = waypoints[i - 1]
				curr_wp = waypoints[i]
				next_wp = waypoints[i + 1]
				
				# Check if the current waypoint is in a row (aligned on either axis)
				if (prev_wp[0] == curr_wp[0] == next_wp[0]) or (prev_wp[1] == curr_wp[1] == next_wp[1]):
					# Skip the current waypoint (remove it)
					i += 1
					continue

			new_waypoints.append(waypoints[i])
			i += 1
		return new_waypoints

	# Apply the function to remove middle waypoints
	# waypoints = remove_middle_if_aligned(waypoints)

	#print(f"Waypoint List Generated: {waypoints}")
	print(f"x positions: {x_points}")
	print(f"y positions: {y_points}")
	print(f"altitude: {alt}")
	#print(f" waypoints: {waypoints}")

	# Check all generated waypoints are within bounds (height, width & alt)
	within_bounds = True
	for wp in waypoints:
		x, y, z, _ = wp # "_" ignores YAW
		if not (-height/2 <= y <= height/2 and -width/2 <= x <= width/2 and z <= alt):
			within_bounds = False
			print(f"Waypoint {wp} is out of bounds!, all waypoints nulled")
			waypoints = 0
			break

	if within_bounds:
		print("All waypoints are within bounds.")

	return waypoints

# This parses the waypoints using the breadcrumb node 
def path_planning(waypoints):

	# Setup ROS
	#rospy.init_node('path_planner', anonymous=True)

	rospy.wait_for_service('/breadcrumb/request_path')
	srvc_bc = rospy.ServiceProxy('/breadcrumb/request_path',RequestPath)

	wps = [] # initialise wps list

	# Loop through the list of waypoints
	for i in range(len(waypoints)-1):
		# Set up a path request for breadcrumb
		# breadcrumb provides a sub-path generated waypoints list such that sub-waypoints are generated between the primary waypoints, 
		# 2 primary waypoints (req.start & req.end) are sent individually, iterating through the entire waypoint list, and sub-waypoints
		# are outputted as wps. 
		# 1) try sending 3 wps to breadcrumb at once
		req = RequestPathRequest()

		# Set start and end point
		req.start.x = waypoints[i][0]
		req.start.y = waypoints[i][1]
		req.start.z = waypoints[i][2]
		req.end.x = waypoints[i+1][0]
		req.end.y = waypoints[i+1][1]
		req.end.z = waypoints[i+1][2]

		res = srvc_bc(req)

		# sparse_path can optimise sub-waypoints generated by breadcrumb in-between the main waypoints
		# print to screen whether sparse_path or path was used (to observe optimisations)
		if len(res.path_sparse.poses) > 0:  # Check if sparse path is available
			rospy.loginfo("Sparse path found between waypoints %d, %d, and %d", i, i + 1, i + 2)
			for pose in res.path_sparse.poses:
				wps.append([pose.position.x, pose.position.y, pose.position.z, 0])
		elif len(res.path.poses) > 0:  # Fallback to full path if sparse is not available
			rospy.loginfo("Full path found between waypoints %d, %d, and %d", i, i + 1, i + 2)
			for pose in res.path.poses:
				wps.append([pose.position.x, pose.position.y, pose.position.z, 0])
		else:
			rospy.logerr("No valid path found for waypoints %d, %d, and %d", i, i + 1, i + 2)
	# return appended wps variable (as new waypoint list)
	print(f"breadcrumb waypoints: {len(wps)}")
	print(f"generated waypoints: {len(waypoints)}")

	return wps

def main(args):
	# Initialise ROS
	rospy.init_node('guidance')

	# List of waypoints
	# [X, Y, Z, Yaw]
	#wps_generated = generate_waypoints(width=8,height=5,spacing=1,edge_offset=1) # old code

	################################# NEW CODE
	# Generate waypoint list using generate_waypoints(...); returns wps_generated
	waypoints = generate_waypoints(width=8,height=5,x_edge_offset=0.5,y_edge_offset=0.5,alt=2)

	# send wps_generated into path_planning() returns wps_pathplanned "path_planning(wps_generated)"; 
	wps = path_planning(waypoints) # make sure to run roslaunch ~/catkin_ws/breadcrumb.launch

	# send wps_pathplanned into Guidance "Guidance(wps_path_planned)"
	guide = Guidance(wps)
	################################# NEW CODE

	#guide = Guidance(wps_generated) # old code

	# Spin!
	rospy.spin()


if __name__ == '__main__':
	try:
		main(sys.argv)
	except rospy.ROSInterruptException:
		pass

	print('')
